name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: 'xregner'
        password: ${{ secrets.dockerpass }} 
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag xtianreg/testing-repo:latest
    - name: push image
      run: docker push xtianreg/testing-repo:latest
